apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: ClusterIP
    kompose.version: 1.35.0 (9532ceef3)
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  ports:
    - name: "8078"
      port: 8078
      targetPort: 8078
  selector:
    io.kompose.service: api-gateway
  type: ClusterIP