apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s-backend/
    kompose.service.type: ClusterIP
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s-backend/
        kompose.service.type: ClusterIP
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start
            - --https-certificate-file=/opt/keycloak/certs/pibbletv.crt
            - --https-certificate-key-file=/opt/keycloak/certs/pibbletv.key
            - --https-port=8443
            - --hostname=auth.pibbletv.com
            - --hostname-strict=false
          env:
            - name: KC_HOSTNAME
              value: auth.pibbletv.com
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTPS_PORT
              value: "8443"
            - name: KC_LOG_LEVEL
              value: debug
            - name: KEYCLOAK_ADMIN
              value: admin1
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_FRONTEND_URL
              value: https://auth.pibbletv.com/auth
          image: quay.io/keycloak/keycloak:26.1.4
          livenessProbe:
            exec:
              command:
                - wget
                - --no-check-certificate
                - -q
                - -O
                - '-'
                - https://localhost:8443/health/ready
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: keycloak
          ports:
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/keycloak/certs
              name: keycloak-claim0
      restartPolicy: Always
      volumes:
        - name: keycloak-claim0
          persistentVolumeClaim:
            claimName: keycloak-claim0
