apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: pibbletv
  labels:
    app: service-registry
spec:
  ports:
    - name: eureka
      port: 8761
      targetPort: 8761
  selector:
    app: service-registry
  type: ClusterIP
