apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: ghcr.io/pibbletv/pibbletv-service-registry:latest
          ports:
            - containerPort: 8761
              protocol: TCP
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://$(SPRING_SECURITY_USER_NAME):$(SPRING_SECURITY_USER_PASSWORD)@service-registry:8761/eureka/
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: username
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: password
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "true"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_COMMONS_UTIL_INETUTILS
              value: TRACE
            - name: LOGGING_LEVEL_COM_NETFLIX_DISCOVERY
              value: DEBUG
            - name: LOGGING_LEVEL_COM_NETFLIX_EUREKA
              value: DEBUG
            - name: SERVER_PORT
              value: "8761"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      imagePullSecrets:
        - name: ghcr-credentials
