services:
  api-gateway:
    image: ghcr.io/pibbletv/pibbletv-gateway:latest
    container_name: api-gateway
    ports:
      - "8078:8078"
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_GATEWAY_URL}
      KEYCLOAK_SSL_REQUIRED: external
      SERVER_PORT: "8078"
      KEYCLOAK_PUBLIC_CLIENT: "false"
    volumes:
      - /home/tanzerdx/certs:/opt/keycloak/certs
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-k", "https://localhost:8078/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - backend

  user-service:
    image: ghcr.io/pibbletv/pibbletv-user-service:latest
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_R2DBC_URL: ${R2DBC_CONNECTION_USER_SERVICE}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      - backend

  donations-service:
    image: ghcr.io/pibbletv/pibbletv-donations-service:latest
    container_name: donations-service
    ports:
      - "8084:8084"
    environment:
      SPRING_R2DBC_URL: ${R2DBC_CONNECTION_DONATIONS_SERVICE}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      - backend

  streaming-service:
    image: ghcr.io/pibbletv/pibbletv-streaming-service:latest
    container_name: streaming-service
    ports:
      - "8085:8085"
    environment:
      SPRING_R2DBC_URL: ${R2DBC_CONNECTION_STREAMING_SERVICE}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      - backend

  category-service:
    image: ghcr.io/pibbletv/pibbletv-category-service:latest
    container_name: category-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_R2DBC_URL: ${R2DBC_CONNECTION_CATEGORY_SERVICE}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      - backend

  follows-service:
    image: ghcr.io/pibbletv/pibbletv-follows-service:latest
    container_name: follows-service
    ports:
      - "8083:8083"
    environment:
      SPRING_R2DBC_URL: ${R2DBC_CONNECTION_FOLLOWS_SERVICE}
      SPRING_R2DBC_USERNAME: ${DB_USER}
      SPRING_R2DBC_PASSWORD: ${DB_PASSWORD}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      - backend

networks:
  backend:
    driver: bridge
