name: api-gateway
services:
  api-gateway:
    container_name: api-gateway
    depends_on:
      service-registry:
        condition: service_healthy
        required: true
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_APPNAME: API-GATEWAY
      EUREKA_INSTANCE_HOSTNAME: api-gateway
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      KEYCLOAK_AUTH_SERVER_URL: https://auth.pibbletv.com/auth
      KEYCLOAK_CREDENTIALS_SECRET: jIt5OvVLRYQ9iDzCGs3utUQVi5S9ogkT
      KEYCLOAK_PUBLIC_CLIENT: "false"
      KEYCLOAK_REALM: pibble-tv
      KEYCLOAK_RESOURCE: pibbletv-api
      KEYCLOAK_SSL_REQUIRED: external
      LOGGING_LEVEL_COM_NETFLIX_DISCOVERY: DEBUG
      LOGGING_LEVEL_COM_NETFLIX_EUREKA: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_COMMONS_UTIL_INETUTILS: TRACE
      SERVER_PORT: "8078"
      SERVER_SSL_CERTIFICATE: file:/opt/keycloak/certs/pibbletv.crt
      SERVER_SSL_CERTIFICATE_PRIVATE_KEY: file:/opt/keycloak/certs/pibbletv.key
      SERVER_SSL_ENABLED: "true"
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
      SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWERCASE_SERVICE_ID: "true"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://auth.pibbletv.com/realms/pibble-tv
      SPRING_SECURITY_USER_NAME: TanzerDx
      SPRING_SECURITY_USER_PASSWORD: serviceRegistryChangedPass784056
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - -k
        - https://localhost:8078/actuator/health
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 1m0s
    image: ghcr.io/pibbletv/pibbletv-gateway:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8078
        published: "8078"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/tanzerdx/certs
        target: /opt/keycloak/certs
        bind:
          create_host_path: true
  category-service:
    container_name: category-service
    depends_on:
      mysql:
        condition: service_healthy
        required: true
      service-registry:
        condition: service_healthy
        required: true
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: category-service
      SPRING_PROFILES_ACTIVE: dev
      SPRING_R2DBC_PASSWORD: Debgubakmo5
      SPRING_R2DBC_URL: r2dbc:mysql://mysql_db/category_service
      SPRING_R2DBC_USERNAME: root
      SPRING_SECURITY_USER_NAME: TanzerDx
      SPRING_SECURITY_USER_PASSWORD: serviceRegistryChangedPass784056
    image: ghcr.io/pibbletv/pibbletv-category-service:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8082
        published: "8082"
        protocol: tcp
  donations-service:
    container_name: donations-service
    depends_on:
      mysql:
        condition: service_healthy
        required: true
      service-registry:
        condition: service_healthy
        required: true
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: donations-service
      SPRING_R2DBC_PASSWORD: Debgubakmo5
      SPRING_R2DBC_URL: r2dbc:mysql://mysql_db/donations_service
      SPRING_R2DBC_USERNAME: root
    image: ghcr.io/pibbletv/pibbletv-donations-service:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8084
        published: "8084"
        protocol: tcp
  follows-service:
    container_name: follows-service
    depends_on:
      mysql:
        condition: service_healthy
        required: true
      service-registry:
        condition: service_healthy
        required: true
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: follows-service
      SPRING_R2DBC_PASSWORD: Debgubakmo5
      SPRING_R2DBC_URL: r2dbc:mysql://mysql_db/follows_service
      SPRING_R2DBC_USERNAME: root
    image: ghcr.io/pibbletv/pibbletv-follows-service:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8083
        published: "8083"
        protocol: tcp
  keycloak:
    command:
      - start
      - --https-certificate-file=/opt/keycloak/certs/pibbletv.crt
      - --https-certificate-key-file=/opt/keycloak/certs/pibbletv.key
      - --https-port=8443
      - --hostname=auth.pibbletv.com
      - --hostname-strict=false
    container_name: keycloak
    environment:
      KC_HOSTNAME: auth.pibbletv.com
      KC_HOSTNAME_STRICT: "false"
      KC_HTTPS_PORT: "8443"
      KC_LOG_LEVEL: debug
      KEYCLOAK_ADMIN: admin1
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: https://auth.pibbletv.com/auth
    healthcheck:
      test:
        - CMD
        - wget
        - --no-check-certificate
        - -q
        - -O
        - '-'
        - https://localhost:8443/health/ready
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 1m0s
    image: quay.io/keycloak/keycloak:26.1.4
    labels:
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8443
        published: "8443"
        protocol: tcp
    volumes:
      - type: bind
        source: /home/tanzerdx/certs
        target: /opt/keycloak/certs
        bind:
          create_host_path: true
  mysql:
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: pibbletv
      MYSQL_ROOT_PASSWORD: Debgubakmo5
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
        - -u
        - root
        - -pDebgubakmo5
      timeout: 10s
      interval: 5s
      retries: 10
    image: mysql:8
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 3306
        published: "3306"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
        volume: {}
  service-registry:
    command:
      - java
      - -Deureka.client.service-url.defaultZone=http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      - -jar
      - /app.jar
    container_name: service-registry
    environment:
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: service-registry
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: "true"
      EUREKA_SERVER_PEER_NODE_URL: http://service-registry:8761/eureka/
      LOGGING_LEVEL_COM_NETFLIX_DISCOVERY: DEBUG
      LOGGING_LEVEL_COM_NETFLIX_EUREKA: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_COMMONS_UTIL_INETUTILS: TRACE
      SERVER_PORT: "8761"
      SPRING_DATASOURCE_PASSWORD: Debgubakmo5
      SPRING_DATASOURCE_USERNAME: root
      SPRING_SECURITY_USER_NAME: TanzerDx
      SPRING_SECURITY_USER_PASSWORD: serviceRegistryChangedPass784056
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8761/actuator/health
      timeout: 10s
      interval: 30s
      retries: 5
    image: ghcr.io/pibbletv/pibbletv-service-registry:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8761
        published: "8761"
        protocol: tcp
  streaming-service:
    container_name: streaming-service
    depends_on:
      mysql:
        condition: service_healthy
        required: true
      service-registry:
        condition: service_healthy
        required: true
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: streaming-service
      SPRING_R2DBC_PASSWORD: Debgubakmo5
      SPRING_R2DBC_URL: r2dbc:mysql://mysql_db/streaming_service
      SPRING_R2DBC_USERNAME: root
    image: ghcr.io/pibbletv/pibbletv-streaming-service:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8085
        published: "8085"
        protocol: tcp
  user-service:
    container_name: user-service
    depends_on:
      mysql:
        condition: service_healthy
        required: true
      service-registry:
        condition: service_healthy
        required: true
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://TanzerDx:serviceRegistryChangedPass784056@service-registry:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: user-service
      SPRING_R2DBC_PASSWORD: Debgubakmo5
      SPRING_R2DBC_URL: r2dbc:mysql://mysql_db/user_service
      SPRING_R2DBC_USERNAME: root
    image: ghcr.io/pibbletv/pibbletv-user-service:latest
    labels:
      kompose.image-pull-secret: ghcr-credentials
      kompose.service.type: ClusterIP
    networks:
      backend: null
    ports:
      - mode: ingress
        target: 8081
        published: "8081"
        protocol: tcp
networks:
  backend:
    name: api-gateway_backend
    driver: bridge
volumes:
  mysql_data:
    name: api-gateway_mysql_data
