global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - default
        selectors:
          - role: pod
            label: "app.kubernetes.io/name=node-exporter"

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']


      - job_name: 'api-gateway'
        scheme: https
        static_configs:
          - targets: [ 'api-gateway:8078' ]
        metrics_path: /actuator/prometheus
        tls_config:
          insecure_skip_verify: true

      - job_name: 'user-service'
        static_configs:
          - targets: [ 'user-service:8081' ]
        metrics_path: /actuator/prometheus

      - job_name: 'category-service'
        static_configs:
          - targets: [ 'category-service:8082' ]
        metrics_path: /actuator/prometheus

      - job_name: 'follows-service'
        static_configs:
          - targets: [ 'follows-service:8083' ]
        metrics_path: /actuator/prometheus

      - job_name: 'donations-service'
        static_configs:
          - targets: [ 'donations-service:8084' ]
        metrics_path: /actuator/prometheus

      - job_name: 'streaming-service'
        static_configs:
          - targets: [ 'streaming-service:8085' ]
        metrics_path: /actuator/prometheus