apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: LoadBalancer
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: api-gateway-tcp
  name: api-gateway-tcp
spec:
  ports:
    - name: "8078"
      port: 8078
      targetPort: 8078
  selector:
    io.kompose.service: api-gateway
  type: LoadBalancer
