apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: ClusterIP
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: donations-service
  name: donations-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    io.kompose.service: donations-service
  type: ClusterIP
