apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: LoadBalancer
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: follows-service-tcp
  name: follows-service-tcp
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: follows-service
  type: LoadBalancer
