apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: LoadBalancer
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: service-registry-tcp
  name: service-registry-tcp
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: service-registry
  type: LoadBalancer
