apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: ClusterIP
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: service-registry
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service-registry
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
        kompose.image-pull-secret: ghcr-credentials
        kompose.service.type: ClusterIP
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: service-registry
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://-:-@service-registry:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: service-registry
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "true"
            - name: LOGGING_LEVEL_COM_NETFLIX_DISCOVERY
              value: DEBUG
            - name: LOGGING_LEVEL_COM_NETFLIX_EUREKA
              value: DEBUG
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_COMMONS_UTIL_INETUTILS
              value: TRACE
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_DATASOURCE_PASSWORD
              value: Debgubakmo5
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_SECURITY_USER_NAME
              value: TanzerDx
            - name: SPRING_SECURITY_USER_PASSWORD
              value: serviceRegistryHehe123
          image: ghcr.io/pibbletv/pibbletv-service-registry:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/actuator/health
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: service-registry
          ports:
            - containerPort: 8761
              protocol: TCP
      imagePullSecrets:
        - name: ghcr-credentials
      restartPolicy: Always
