apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
    kompose.image-pull-secret: ghcr-credentials
    kompose.service.type: ClusterIP
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: streaming-service
  name: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streaming-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f merged-backend.yml -o k8s/
        kompose.image-pull-secret: ghcr-credentials
        kompose.service.type: ClusterIP
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: streaming-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://TanzerDx:serviceRegistryHehe123@service-registry:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: streaming-service
            - name: SPRING_R2DBC_PASSWORD
              value: Debgubakmo5
            - name: SPRING_R2DBC_URL
              value: r2dbc:mysql://mysql_db/streaming_service
            - name: SPRING_R2DBC_USERNAME
              value: root
          image: ghcr.io/pibbletv/pibbletv-streaming-service:latest
          name: streaming-service
          ports:
            - containerPort: 8085
              protocol: TCP
      imagePullSecrets:
        - name: ghcr-credentials
      restartPolicy: Always
